export const LOAD_SCHEDULE_BEGIN = "LOAD_SCHEDULE_BEGIN";
export const LOAD_SCHEDULE_SUCCESS = "LOAD_SCHEDULE_SUCCESS";
export const LOAD_SCHEDULE_FAILURE = "LOAD_SCHEDULE_FAILURE";
export const CNANGE_PERFORMANCE_STATUS = "CNANGE_PERFORMANCE_STATUS";
export const CNANGE_CHOSENPERFORMANCE_STATUS = "CNANGE_CHOSENPERFORMANCE_STATUS";
