export const LOAD_PERFORMANCES_BEGIN = 'LOAD_PERFORMANCES_BEGIN';
export const LOAD_PERFORMANCES_SUCCESS = 'LOAD_PERFORMANCES_SUCCESS';
export const LOAD_PERFORMANCES_END = 'LOAD_PERFORMANCES_END';
export const FILTER_PERFORMANCES = 'FILTER_PERFORMANCES';
