export const LOAD_PERFORMANCES_BEGIN = "LOAD_PERFORMANCES_BEGIN";
export const LOAD_PERFORMANCES_SUCCESS = "LOAD_PERFORMANCES_SUCCESS";
export const LOAD_PERFORMANCES_FAILURE = "LOAD_PERFORMANCES_FAILURE";
