export const FETCH_PERFORMANCE_REQUEST = 'FETCH_PERFORMANCE_REQUEST';

export const FETCH_PERFORMANCE_SUCCESS = 'FETCH_PERFORMANCE_SUCCESS';

export const FETCH_PERFORMANCE_FAILURE = 'FETCH_PERFORMANCE_FAILURE';

export const FETCH_LANGUAGES_SUCCESS = 'FETCH_LANGUAGES_SUCCESS'

export const TOGGLE_PERF = 'TOGGLE_PERF';

export const TOGGLE_LANG = 'TOGGLE_LANG';

export const TOGGLE_ISCONNECTED = "TOGGLE_ISCONNECTED"

export const TOGGLE_CONNECTION = "TOGGLE_CONNECTION"

