export const STORE_PROFILE_UPDATES_BEGIN = "STORE_PROFILE_UPDATES_BEGIN";
export const STORE_PROFILE_UPDATES_SUCCESS = "STORE_PROFILE_UPDATES_SUCCESS";
export const STORE_PROFILE_UPDATES_FAILURE = "STORE_PROFILE_UPDATES_FAILURE";

export const STORE_PASSWORD_UPDATE_BEGIN = "STORE_PASSWORD_UPDATE_BEGIN";
export const STORE_PASSWORD_UPDATE_SUCCESS = "STORE_PASSWORD_UPDATE_SUCCESS";
export const STORE_PASSWORD_UPDATE_FAILURE = "STORE_PASSWORD_UPDATE_FAILURE";