export const SET_APP_READY = "SET_READY";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const CHANGE_SCREEN = "CHANGE_SCREEN";
export const FONT_LOADING_BEGIN = "FONT_LOADING_BEGIN";
export const FONT_LOADING_SUCCESS = "FONT_LOADING_SUCCESS";
