export const LOAD_WISHLIST_BEGIN = "LOAD_WISHLIST_BEGIN";
export const LOAD_WISHLIST_SUCCESS = "LOAD_WISHLIST_SUCCESS";
export const LOAD_WISHLIST_FAILURE = "LOAD_WISHLIST_FAILURE";
export const STORE_PERFORMANCE_BEGIN = "STORE_PERFORMANCE_BEGIN";
export const STORE_PERFORMANCE_SUCCESS = "STORE_PERFORMANCE_SUCCESS";
export const STORE_PERFORMANCE_FAILURE = "STORE_PERFORMANCE_FAILURE";
<<<<<<< HEAD
=======
export const ADD_TO_WISHLIST= "ADD_TO_WISHLIST";
>>>>>>> 8811512d2a6e564bf2eb79b038fcb059ab4601ba
export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST";