export const SAVE_OR_DELETE_PERFORMANCE = "SAVE_OR_DELETE_PERFORMANCE";
export const LOAD_PERFORMANCE_BEGIN = "LOAD_PERFORMANCE_BEGIN";
export const LOAD_PERFORMANCE_SUCCESS = "LOAD_PERFORMANCE_SUCCESS";
export const LOAD_PERFORMANCE_FAILURE = "LOAD_PERFORMANCE_FAILURE";
export const STORE_PERFORMANCE_BEGIN = "STORE_PERFORMANCE_BEGIN";
export const STORE_PERFORMANCE_SUCCESS = "STORE_PERFORMANCE_SUCCESS";
export const STORE_PERFORMANCE_FAILURE = "STORE_PERFORMANCE_FAILURE";