export const LOAD_PERFORMANCE_BEGIN = "LOAD_PERFORMANCE_BEGIN";
export const LOAD_PERFORMANCE_SUCCESS = "LOAD_PERFORMANCE_SUCCESS";
export const LOAD_PERFORMANCE_FAILURE = "LOAD_PERFORMANCE_FAILURE";
export const CNANGE_STATUS_PERFORMANCE = "CNANGE_STATUS_PERFORMANCE";